dist: trusty
sudo: false
language: python
python:
    - "3.5"
install:
    - pip install -U pip setuptools wheel
    - pip install -U -r requirements-test.txt
    - pip install -e .
script:
    - py.test --cov-config .coveragerc --cov=kpkontrol
after_success:
    - coverage combine
    - coveralls
